### PR TITLE
Fix issues #4, #5, #6, #7

### LINKED ISSUE #4: Set vibrato parameters at the beginning or end of processBlock

### LINKED ISSUE #5: Use value tree for parameter caching
https://docs.juce.com/master/tutorial_audio_processor_value_tree_state.html
https://forum.juce.com/t/updating-gui-upon-preset-load-in-plugins/37445/2

### LINKED ISSUE #6: Make bypass an int and multiply it with modwidth

### LINKED ISSUE #7: Have a wider frequency modualtion range
0~14Hz

### PR DESCRIPTION
**Pull request by yilin-zhang**
Resolves #4, resolves #5, resolves #6, resolves #7.

### CODE REVIEW

File: VibratoPlugin/Source/PluginProcessor.cpp [hunk 1]
```diff
@@ -24,12 +24,18 @@ VibratoPluginAudioProcessor::VibratoPluginAudioProcessor() :
...
+                {
+                    std::make_unique<AudioParameterFloat>("freqInHz", "Frequency", 0.0f, 14.0f, 0.0f), // 0~14Hz
+                    std::make_unique<AudioParameterFloat>("widthInMs", "Width", 0.0f, 100.0f, 0.0f),   // 0~100ms
+                    std::make_unique<AudioParameterBool>("bypassed", "Bypassed", false)
+                })
 {
     CVibrato::createInstance(vibrato);
+    m_fParamFreqInHz = parameters.getRawParameterValue ("freqInHz");
+    m_fParamWidthInMs = parameters.getRawParameterValue ("widthInMs");
+    m_fParamBypassed = parameters.getRawParameterValue ("bypassed"); // 0.0f or 1.0f
```
Comment (kaushalsali) [inline VibratoPlugin/Source/PluginProcessor.cpp:38]: Build fails unless a `reinterpret_cast<std::atomic<float> *>()` is used here.

File: VibratoPlugin/Source/PluginProcessor.cpp [hunk 2]
```diff
@@ -24,12 +24,18 @@ VibratoPluginAudioProcessor::VibratoPluginAudioProcessor() :
                     ),
 #endif
      vibrato(nullptr),
```
Comment (kaushalsali) [inline VibratoPlugin/Source/PluginProcessor.cpp:26]: `vibrato` should be renamed to `m_pVibrato` in all usages.

File: VibratoPlugin/Source/PluginProcessor.cpp [hunk 3]
```diff
@@ -157,13 +163,13 @@ void VibratoPluginAudioProcessor::processBlock (AudioBuffer<float>& buffer, Midi
...
-//
-//        // ..do something to the data...
-//    }
 
+    float modWidthInS = *m_fParamWidthInMs / 1000;
+    float modFreqInHz = *m_fParamFreqInHz;
+    int bypassed = round(*m_fParamBypassed);
+
+    vibrato->setParam(CVibrato::kParamModWidthInS, modWidthInS * static_cast<float>(1-bypassed));
+    vibrato->setParam(CVibrato::kParamModFreqInHz, modFreqInHz);
```
Comment (kaushalsali) [inline VibratoPlugin/Source/PluginProcessor.cpp:172]: Setting params again and again for each block seems redundant. I don't think this should be done in `processBlock` (on the audio thread). In the previous implementation, the GUI thread was responsible for setting the params which would be done only when a change was made by the user.

**Review by kaushalsali — CHANGES_REQUESTED** [review]
